#### general settings
name: default
max_matlab_start : 1

#### Train Settings
Hyper_array:
  h0:
    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit'
    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup'
#  h1:
#    VALVE_SIMULATION_MODEL: 'sm_DDPG_Training_Circuit'
#  h2:
#    VALVE_SIMULATION_MODEL: 'sm_DDPG_Training_Circuit'
