#### general settings
name: default3_lastaction4
max_matlab_start : 4
task_type:
  train: false
  test: true
  test_sample_time: 10080.0

#### Train Settings
Hyper_array:
  h0:
    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h0'
    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
    batch: 64.0
    max_eps: 6000.0
    ACCEPTABLE_DELTA : 0.04
    action_range: [1.0, 21.0]

    criticLearningRate : 0.00001
    actorLearningRate  : 0.000001

    agent_sample_time : 1.0
    maxsteps: 2000.0      #每局游戏最大步长

    SAVE_AGENT_THRESHOLD  : 2000.0 * 10 * 0.8
    STOP_TRAINING : 2000.0 * 10 * 0.9
#
#  h1:
#    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h1'
#    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
#    batch: 64.0
#    max_eps: 6000.0
#    ACCEPTABLE_DELTA: 0.04
#    action_range: [1.0, 21.0]
#
#    criticLearningRate: 0.000005
#    actorLearningRate: 0.0000005
#
#    agent_sample_time: 1.0
#    maxsteps: 2000.0      #每局游戏最大步长
#
#    SAVE_AGENT_THRESHOLD  : 2000.0 * 10 * 0.8
#    STOP_TRAINING : 2000.0 * 10 * 0.9
#
##  h2:
##    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h2'
##    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
##    batch: 64.0
##    max_eps: 5000.0
##    ACCEPTABLE_DELTA: 0.04
##    action_range: [1.0, 21.0]
##
##    criticLearningRate : 0.0001
##    actorLearningRate  : 0.00001
##
##    agent_sample_time: 1.0
##    maxsteps: 20000.0      #每局游戏最大步长
##
##    SAVE_AGENT_THRESHOLD  : 2000.0 * 10 * 0.8
##    STOP_TRAINING : 2000.0 * 10 * 0.9
#
#  h3:
#    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h3'
#    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
#    batch: 64.0
#    max_eps: 6000.0
#    ACCEPTABLE_DELTA: 0.04
#    action_range: [1.0, 21.0]
#
#    criticLearningRate : 0.00005
#    actorLearningRate  : 0.000005
#
#    agent_sample_time: 1.0
#    maxsteps: 2000.0      #每局游戏最大步长
#
#    SAVE_AGENT_THRESHOLD  : 2000.0 * 10 * 0.8
#    STOP_TRAINING : 2000.0 * 10 * 0.9
#
#  h4:
#    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h4'
#    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
#    batch: 32.0
#    max_eps: 4000.0
#    ACCEPTABLE_DELTA: 0.04
#    action_range: [1.0, 21.0]
#
#    criticLearningRate: 0.00008
#    actorLearningRate: 0.000008
#
#    agent_sample_time: 0.4
#    maxsteps: 5000.0      #每局游戏最大步长
#
#    SAVE_AGENT_THRESHOLD  : 5000.0 * 10 * 0.8
#    STOP_TRAINING : 5000.0 * 10 * 0.9