#### general settings
name: default
max_matlab_start : 1
task_type:
  train: true
  test: true

  test_sample_time: 10.0

#### Train Settings
Hyper_array:
  h0:
    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h0'
    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
    batch: 128.0
    max_eps: 2.0
    ACCEPTABLE_DELTA : 0.04
    action_range: [0.001, 0.23]

  h1:
    VALVE_SIMULATION_MODEL_Train: 'sm_DDPG_Training_Circuit_h0'
    VALVE_SIMULATION_MODEL_Test: 'sm_Experimental_Setup_h0'
    batch: 128.0
    max_eps: 2.0
    ACCEPTABLE_DELTA: 0.04
    action_range: [ 0.001, 0.23 ]
